# Generated by Django 3.2.2 on 2021-05-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=6)),
                ('email', models.EmailField(default='', max_length=10)),
            ],
        ),
    ]
