# Generated by Django 3.2.2 on 2021-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='signup',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
